title: RetroTerminal
description: CRT-styled blog
url: https://retroterminal.net

permalink: pretty
markdown: kramdown

collections:
  recipes:
    output: true
    permalink: /recipes/:name/
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:title/

  - scope:
      path: ""
      type: "recipes"
    values:
      layout: default
