title: RetroTerminal
description: CRT-styled blog
url: https://retroterminal.net
tabs_nav_url: /tabs/
tabs_index_url: https://tabs.retroterminal.net/data/tabs.json
tabs_file_base_url: https://tabs.retroterminal.net
tabs_upload_url: https://tabs.retroterminal.net/upload

permalink: pretty
markdown: kramdown

collections:
  recipes:
    output: true
    permalink: /recipes/:name/
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:title/

  - scope:
      path: ""
      type: "recipes"
    values:
      layout: default
