server {
    listen 80;
    server_name tabs.retroterminal.net;
    client_max_body_size 25m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
        default_type "text/plain";
        allow all;
    }

    location / {
        proxy_pass http://100.112.11.1:4080;
        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header Connection        "";

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
